version: '3.9'
name: cylimit-local

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: cylimit
    ports:
      - 27444:27017
    volumes:
      - mongo-db:/data/db
    networks:
      - mongo-network

volumes:
  mongo-db:

networks:
  mongo-network:
    driver: bridge
