version: '3.9'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6380" #both numbers must match port in command below AND REDIS_PORT cheapotle service variable
    command: redis-server --port 6380

  cylimit-api-staging:
    image: 250828633224.dkr.ecr.ap-southeast-1.amazonaws.com/cylimit:latest
    depends_on:
      - redis
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-3
        awslogs-group: apps/cylimit-api
        awslogs-create-group: "true"
    container_name: "api"
    env_file:
      - ./.env.prod
    environment:
        - PORT=4000
        - BASE_URL=https://api.cylimit.com/v1
        - REDIS_HOST=redis
        - REDIS_PORT=6380
        - REDIS_PASSWORD=123456
        - CLIENT_BASE_URL=https://app.cylimit.com
        - CLIENT_VERIFY_URL=https://app.cylimit.com/email-verified
        - CLIENT_FORGOT_PASSWORD_URL=https://app.cylimit.com/reset-password
    restart: on-failure
    ports:
      - 4000:4000
