################################################################################
# CLOUD BUILD CONFIGURATION - PAGE MAINTENANCE
################################################################################
#
# OBJECTIF :
# Builder et pusher l'image Docker de la page maintenance vers GCR
#
# POURQUOI :
# - Build dans le cloud (pas besoin de Docker local)
# - Push automatique vers Google Container Registry
# - Prêt pour déploiement sur Cloud Run
#
# COMMENT :
# gcloud builds submit --config cloudbuild.maintenance.yaml
#
# APPELÉ DEPUIS : Script deploy-maintenance.sh
# APPELLE : Dockerfile.maintenance pour créer l'image nginx
#
################################################################################

steps:
  # Étape 1 : Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'maintenance/Dockerfile.maintenance',
      '-t', '${_IMAGE_NAME}',
      'maintenance'
    ]
    id: 'build-image'

  # Étape 2 : Push de l'image vers GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
    id: 'push-image'

# Configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Sauvegarder l'image dans GCR
images:
  - '${_IMAGE_NAME}'

# Timeout total
timeout: 600s

